### PR TITLE
Poetry based setup

### PR DESCRIPTION
**Pull request by heliocastro**
This is the Poetry based setup. Is targeted to Python 3.9.
Some ruff format fixes are applied. No mypy or ruff error reports fixed yet.
One gh action to run and verify the commits  are added.

For development i use this steps:

```bash
pip install poetry pre-commit
pre-commit install 
pre-commit install --hook-type commit-msg
```

You can run locally pre-commit this way:
```bash
pre-commit run --all
```

### CODE REVIEW

**Comment by heliocastro** [comment]
@acederberg Since you do not have a main branch i pointed out to releases/v2. But i do suggest you create a main branch.

**Comment by heliocastro** [comment]
@acederberg I pushed the rest of my changes, that is a small refactor:
* Update to python 3.9 base
* Fixed all mypy and ruff reports
* Added Path from pathlib as a possibility to the file list

Hope you find some usage on this

**Comment by heliocastro** [comment]
> @acederberg Since you do not have a main branch i pointed out to releases/v2. But i do suggest you create a main branch.

Btw, i pick before the changes on 2.2.0, so there are some conflicts

**Comment by acederberg** [comment]
@heliocastro 

Thank you for your contributions! I will review this and merge much of it later on today or early tomorrow when I've got some time to check it out in entirety. You are correct, there should be a master branch. 

I would like to also mention that there are some more changes likely incoming that will deprecate ``fileDummies`` and the other ``pytest`` fixtures in favor of the built in ``tmp_path`` fixture. This will require a more direct setup in some tests, but will make tests much more clear.

**Comment by acederberg** [comment]
@heliocastro I did my best to resolve the changes here on github. I'm going to pull this all and get everything working. The only thing I actively left out from your changes were the ``Dict -> dict`` changes, which I will just fix manually on my end

**Comment by heliocastro** [comment]
After that, I will be glad to make pra direcy on your side, to help.
I found a bug on the clas init that I will describe better after you finished 
Again, I'm all to help if you need

**Comment by acederberg** [comment]
@heliocastro It looks like we're ready after those recent commits. I also decided that I would like to ignore a few more things under ``ruff`` and fixed some ``mypy`` complaints. I cannot find exactly what happened such that actions failed, it appears to be ``mypy`` but I cannot get the output as it is appended to a file. Further running the exact command locally I have no issues. Are the contents of that file accessible somewhere?

**Comment by heliocastro** [comment]
They are redirected to the summary of the job, but still not the best implementation. If you click on Summary ( left top on job interface ) you will se the results. Tomorrow I will do a PR where the results will be stored if fails

**Comment by acederberg** [comment]
Alright, this passes commit validation. ~~Any remaining changes you'd like to make on this PR @heliocastro?~~

It has been merged.

**Review by acederberg — APPROVED** [review]

**Comment by heliocastro** [comment]
Perfect :-) Thanks. I will abandon my branch and back to the upstream !

**Pull request merged**
